### ISSUE TITLE
OSError: [Errno 5] EIO

### ISSUE THREAD

**Issue by ouzhoucheng** [bunny1985/mpu6050_DMP_python#2]
I use Thonny and download all .py into pico
then I run MPU6050_example.py or MPU6050_cal.py
then error occurs 
```
Traceback (most recent call last):
  File "<stdin>", line 33, in <module>
  File "MPU6050RPI.py", line 100, in __init__
  File "MPU6050RPI.py", line 213, in set_clock_source
  File "MPU6050RPI.py", line 143, in write_bits
  File "usmbus.py", line 29, in read_byte_data
OSError: [Errno 5] EIO
```
I found the place
```
line 29   return self.readfrom_mem(addr, register, 1)[0]
```
I don't know how to fix it
by the way, I have not found any information about init pins, it is the problem factors?

**Comment by ouzhoucheng** [comment]
my wire is loose, sorry

**Comment by alhaddad-m** [comment]
@ouzhoucheng  Could you tell me how do you set the pins and does it work with pico without modifications? Thanks in advance.
